import type { Metadata } from "next";
import { Footer, Header } from "../components/SiteChrome";
import { SUPPORT_EMAIL } from "../config";
import { PrivacyPreferences } from "../components/PrivacyPreferences";

export const metadata: Metadata = { title: "Privacy Policy | Say No to Plastic", alternates: { canonical: "/privacy-policy" } };

export default function PrivacyPage() {
  return <><Header/><main id="main-content" tabIndex={-1} className="inner-page legal-page"><section><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p className="legal-date">Last updated August 9, 2026</p></section><article>
    <h2>Who operates this site</h2><p>Say No to Plastic operates this publishing, education, and ecommerce website for a primarily United States audience. Privacy questions can be sent to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
    <h2>What this policy covers</h2><p>This policy applies to website reading activity, ebook purchase and access systems, subscriber forms, the requested ten-part learning series, device-local worksheets and challenge progress, contact inquiries, optional analytics, affiliate links, and support communications controlled by Say No to Plastic. A retailer, checkout provider, or other outside service has its own policy for information it controls.</p>
    <h2>Information you provide</h2><p>We collect the name, email address, source page, requested email program, consent version, and submission time associated with an email signup. Learning-series enrollment state includes the sequence identifier, next lesson, status, and relevant timestamps so requested lessons can be scheduled and stopped when a person unsubscribes. Contact inquiries include the name, email address, topic, message, and time submitted. Do not send medical records, payment-card information, or sensitive health information through these forms.</p>
    <h2>Orders and ebook access</h2><p>Book purchases may be routed through the legacy Homo Plasticus WooCommerce store or a hosted Stripe checkout, depending on the purchase system currently activated. The payment provider processes the contact, billing, transaction, fraud-prevention, and technical information needed to complete the payment. Say No to Plastic does not store full payment-card numbers.</p><p>When the first-party ebook access system is active, Say No to Plastic stores an internal order identifier, payment-provider identifiers, purchase email, amount, currency, source, payment and access status, and relevant timestamps. Secure access, download, refund-revocation, delivery, and recovery events are recorded so the order can be fulfilled and supported. Recovery requests use a protected email-derived value for rate limiting and do not publicly confirm whether an order exists.</p>
    <h2>Device-local worksheets and challenges</h2><p>The exposure worksheet, ten-reading progress tracker, and 7-day and 30-day challenges can save selections in your browser storage so progress remains available on that device. Those saved choices are not submitted to Say No to Plastic unless you separately send information through a form. You can reset each tool in the interface or clear the site data in your browser.</p>
    <h2>Optional first-party analytics</h2><p>If you select “Allow anonymous analytics,” the site records page paths, referring pages, selected actions, outbound destinations, an ephemeral session identifier, and timestamps. We do not intentionally store your IP address in the Say No to Plastic analytics table. Selecting “Essential only” prevents this optional event collection on that device.</p>
    <h2>Email delivery</h2><p>Subscriber, contact, and ebook-delivery records are stored in the site's database. When production email delivery is active, Resend may process contact and delivery information for welcome messages, requested scheduled learning-series lessons, broadcasts, preference management, contact notifications, purchase access, and access recovery. Every marketing message must include a method to unsubscribe; transactional purchase messages may still be sent when needed to fulfill or support an order.</p>
    <h2>How information is used</h2><p>We use information to operate and secure the site, process and document purchases, fulfill and recover ebook access, respond to inquiries, deliver requested emails, understand useful content, improve the purchase journey, prevent abuse, maintain records, and comply with legal obligations.</p>
    <h2>Affiliate links and outside stores</h2><p>Affiliate links may include identifiers that allow a retailer to attribute a purchase. When you follow such a link, the retailer controls its own cookies, order information, shipping, support, returns, and privacy practices. Affiliate relationships are disclosed near relevant links.</p>
    <h2>Service providers</h2><p>Service providers may include Cloudflare for website, database, and private-file infrastructure; WooCommerce or Stripe and related payment processors; Resend for email delivery; security and anti-spam systems; and optional measurement services. Providers receive information needed to perform their function and operate under their own legal obligations.</p>
    <h2>Retention</h2><p>Subscriber and learning-series enrollment records are retained while a subscription or requested sequence remains active and as needed to complete delivery, honor unsubscribe requests, document consent, and prevent unwanted rescheduling. Contact, order, fulfillment, recovery, and download-support records are retained for operational, fraud-prevention, tax, accounting, security, and legal needs. Analytics records may be aggregated or deleted when detailed event data is no longer useful.</p>
    <h2>Your choices and rights</h2><p>You may unsubscribe from marketing emails, decline optional analytics, or request access, correction, or deletion of information associated with your email where applicable. Some records may be retained when required for transactions, security, legal obligations, or suppression of future marketing.</p>
    <h2>Sale and advertising</h2><p>Say No to Plastic does not sell personal information. The site does not use third-party behavioral advertising trackers. If that practice changes, this policy and the site's privacy choices will be updated before activation.</p>
    <h2>Children</h2><p>The site is intended for a general adult audience and does not knowingly collect personal information from children under 13.</p>
    <h2>Security</h2><p>Reasonable technical and organizational measures are used to protect records. Ebook files are intended to remain in private storage and access links are signed and time limited. No internet system can guarantee absolute security. Contact us if you believe information submitted through the site has been compromised.</p>
    <h2>Changes</h2><p>This policy may change as services, purchase systems, or legal requirements evolve. The revision date appears at the top of the page.</p>
  </article><div id="privacy-choices"><PrivacyPreferences /></div></main><Footer/></>;
}
