export type Guide = {
  slug: string;
  category: string;
  title: string;
  description: string;
  readingTime: string;
  takeaway: string;
  known: string[];
  uncertain: string[];
  actions: string[];
  sources: { label: string; title: string; href: string }[];
  publishedDate?: string;
  updatedDate?: string;
  featured?: boolean;
  audience?: string;
};

export const guides: Guide[] = [
  {
    slug: "microplastics-drinking-water-filter-guide",
    category: "Water",
    title: "Drinking water: avoid plastic bottles and choose a filter you can maintain",
    description: "A direct starting point for plastic bottles, glass or steel drinkware, reverse osmosis, activated carbon, and filter upkeep.",
    readingTime: "6 minute read",
    audience: "Everyday water routines",
    featured: true,
    publishedDate: "2026-08-06",
    updatedDate: "2026-08-06",
    takeaway: "First, avoid routine plastic water bottles when practical. Carry water in glass or stainless steel. For home filtration, reverse osmosis is one option worth comparing with your local water quality, certified reduction claims, maintenance, and wastewater use.",
    known: [
      "Microplastic particles have been reported in both bottled and tap water.",
      "Reported particle counts vary greatly because sampling and detection methods differ.",
      "Membrane-based systems, including reverse osmosis, can physically reduce particles within their rated performance range.",
      "Activated-carbon systems are designed for specific contaminants and should not be assumed to remove every particle or chemical.",
    ],
    uncertain: [
      "There is no single household-filter certification dedicated to every microplastic size and polymer.",
      "Particle counts alone do not establish a person's absorbed dose or clinical risk.",
      "A product claim may rely on laboratory conditions that differ from household use.",
      "The right system depends on local water quality, access, cost, maintenance, and other contaminants that matter in the home.",
    ],
    actions: [
      "Avoid routine plastic water bottles when a safe, practical alternative is available.",
      "Use a durable glass or stainless-steel bottle or cup for the water you carry most often.",
      "Read your local utility's water-quality report before buying a system.",
      "If you are considering reverse osmosis, compare certified reduction claims, filter replacement, wastewater use, installation, and maintenance.",
      "Replace cartridges on schedule; an unmaintained filter is not a useful solution.",
    ],
    sources: [
      { label: "World Health Organization", title: "Microplastics in drinking-water", href: "https://www.who.int/publications/i/item/9789241516198" },
      { label: "PNAS", title: "Rapid single-particle chemical imaging of nanoplastics in bottled water", href: "https://pubmed.ncbi.nlm.nih.gov/38190543/" },
      { label: "U.S. EPA", title: "Consumer confidence reports", href: "https://www.epa.gov/ccr" },
      { label: "NSF", title: "Standards for water treatment systems", href: "https://www.nsf.org/consumer-resources/articles/standards-water-treatment-systems" },
    ],
  },
  {
    slug: "heating-food-in-plastic",
    category: "Kitchen",
    title: "Heating and storing food: keep plastic out of the routine",
    description: "The direct rule for microwaving, reheating, hot food, leftovers, and everyday food storage.",
    readingTime: "6 minute read",
    audience: "Kitchen routines",
    featured: true,
    publishedDate: "2026-08-06",
    updatedDate: "2026-08-06",
    takeaway: "Do not microwave or reheat food in plastic. Store routine food in glass, ceramic, or stainless steel when practical. There is no need to cool hot food and then move it into plastic storage.",
    known: [
      "Heat can increase the movement of some substances from food-contact materials into food.",
      "Wear, scratches, and repeated use can change a container's surface over time.",
      "Food-contact approvals address intended uses and do not mean a material is chemically inert.",
      "Glass, suitable ceramic, and stainless steel provide durable alternatives for many hot-food and storage uses.",
    ],
    uncertain: [
      "Products vary in polymer, additives, manufacturing quality, age, and intended temperature range.",
      "Laboratory release measurements cannot be translated directly into individual health outcomes.",
      "Terms such as microwave-safe primarily describe intended performance and handling conditions.",
      "The health significance of detected micro- and nanoplastic release remains under study.",
    ],
    actions: [
      "Never microwave or reheat food in plastic.",
      "Use glass or suitable ceramic for reheating.",
      "Store routine food in glass, ceramic, or stainless steel when practical.",
      "Move takeout food into a reusable non-plastic dish before reheating or long storage.",
      "When replacing kitchen items, start with the plastic tools and containers that touch hot food or are used every day.",
    ],
    sources: [
      { label: "U.S. FDA", title: "Microplastics and nanoplastics in foods", href: "https://www.fda.gov/food/environmental-contaminants-food/microplastics-and-nanoplastics-foods" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
      { label: "National Institute of Environmental Health Sciences", title: "Endocrine disruptors", href: "https://www.niehs.nih.gov/health/topics/agents/endocrine" },
      { label: "American Academy of Pediatrics", title: "Food additives and child health", href: "https://pubmed.ncbi.nlm.nih.gov/30037972/" },
    ],
  },
  {
    slug: "microplastics-indoor-dust",
    category: "Home",
    title: "Microplastics in indoor dust: a calmer household response",
    description: "Why fibers accumulate indoors and which cleaning, ventilation, and purchasing habits are reasonable.",
    readingTime: "7 minute read",
    takeaway: "Indoor particles come from many sources. Consistent ventilation, damp cleaning, and filtered vacuuming are more useful than trying to create a particle-free home.",
    known: [
      "Synthetic textiles and furnishings can shed fibers during normal use and wear.",
      "Indoor dust can contain microplastic particles alongside many other particle types.",
      "Smaller particles can remain airborne while larger particles settle on surfaces.",
      "Children may have higher dust contact because of hand-to-mouth behavior and time near floors.",
    ],
    uncertain: [
      "Household concentration measurements vary with sampling location and analytical method.",
      "Measured dust levels do not directly establish the amount retained by the body.",
      "The relative contribution of each textile or furnishing is difficult to isolate in a real home.",
      "No cleaning routine can eliminate exposure from all indoor and outdoor sources.",
    ],
    actions: [
      "Damp-dust hard surfaces instead of repeatedly moving dry dust into the air.",
      "Vacuum regularly with a well-sealed, appropriately filtered machine.",
      "Ventilate when outdoor air quality and weather make it reasonable.",
      "Wash hands before eating, especially for young children who play on floors.",
      "When textiles wear out, consider durable natural-fiber alternatives where they fit the use.",
    ],
    sources: [
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
      { label: "U.S. EPA", title: "What is a HEPA filter?", href: "https://www.epa.gov/indoor-air-quality-iaq/what-hepa-filter" },
      { label: "U.S. EPA", title: "Indoor air quality", href: "https://www.epa.gov/indoor-air-quality-iaq" },
      { label: "Environmental Science & Technology", title: "Microplastics in air and indoor dust", href: "https://pubs.acs.org/doi/10.1021/acs.est.1c04774" },
    ],
  },
  {
    slug: "infant-feeding-plastic-bottles",
    category: "Families",
    title: "Infant feeding and plastic bottles: practical context without blame",
    description: "What particle-release studies do and do not show, plus preparation steps parents can discuss with pediatric professionals.",
    readingTime: "9 minute read",
    takeaway: "Infant feeding decisions involve nutrition, safety, access, and practicality. Particle-release findings support careful preparation and product handling without assigning blame to parents.",
    known: [
      "A laboratory study reported particle release from polypropylene infant-feeding bottles during formula preparation.",
      "Temperature and agitation influenced release under the study conditions.",
      "Infancy is a period of rapid development and high intake relative to body size.",
      "Sterilization and safe formula preparation remain essential for preventing infectious risk.",
    ],
    uncertain: [
      "Particle release estimates vary by bottle, procedure, water, and measurement method.",
      "Release into prepared formula does not establish absorption or a specific health effect.",
      "Alternatives can introduce their own handling, breakage, cost, or availability tradeoffs.",
      "Evidence is not sufficient to justify unsafe departures from pediatric feeding guidance.",
    ],
    actions: [
      "Follow pediatric and public-health instructions for sterilization and formula safety first.",
      "Avoid improvising preparation methods that increase infection or burn risk.",
      "Discuss bottle materials and preparation routines with a pediatric professional when concerned.",
      "Inspect bottles and components for wear, damage, and manufacturer replacement guidance.",
      "Keep the focus on safe feeding and realistic risk reduction rather than parental guilt.",
    ],
    sources: [
      { label: "Nature Food", title: "Microplastic release from polypropylene feeding bottles", href: "https://www.nature.com/articles/s43016-020-00171-y" },
      { label: "CDC", title: "Infant formula preparation and storage", href: "https://www.cdc.gov/infant-toddler-nutrition/formula-feeding/preparation-and-storage.html" },
      { label: "World Health Organization", title: "Safe preparation, storage and handling of powdered infant formula", href: "https://www.who.int/publications/i/item/9789241595414" },
      { label: "American Academy of Pediatrics", title: "Formula feeding guidance", href: "https://www.healthychildren.org/English/ages-stages/baby/formula-feeding/Pages/default.aspx" },
    ],
  },
  {
    slug: "microplastics-carotid-plaque-study",
    category: "Evidence",
    title: "The carotid plaque study: what the 2024 finding actually means",
    description: "A plain-language reading of the cardiovascular study that moved microplastics closer to clinical medicine.",
    readingTime: "10 minute read",
    takeaway: "The study reported a concerning association between detected particles in carotid plaque and later cardiovascular events. It did not prove that the particles caused those events.",
    known: [
      "The study followed patients who underwent surgery for carotid artery disease.",
      "Researchers reported polyethylene in a portion of removed plaque samples.",
      "Patients with detected micro- and nanoplastics experienced more composite cardiovascular events during follow-up.",
      "The work connected tissue detection with clinical outcomes in an observational design.",
    ],
    uncertain: [
      "Observational association cannot establish causation.",
      "Patients with and without detected particles may have differed in unmeasured ways.",
      "The study population already had significant vascular disease and does not represent every adult.",
      "Detection methods and thresholds in human tissue continue to evolve.",
    ],
    actions: [
      "Do not change cardiovascular medication or treatment based on this study.",
      "Continue evidence-based prevention such as blood-pressure, lipid, diabetes, and tobacco-risk management.",
      "Use the finding as a reason for stronger research and reasonable exposure-reduction habits.",
      "Ask whether a summary clearly distinguishes association from causation.",
      "Read the study methods and limitations before sharing an alarming headline.",
    ],
    sources: [
      { label: "New England Journal of Medicine", title: "Microplastics and nanoplastics in atheromas and cardiovascular events", href: "https://pubmed.ncbi.nlm.nih.gov/38446676/" },
      { label: "American Heart Association", title: "Understanding cardiovascular risk", href: "https://www.heart.org/en/health-topics/consumer-healthcare/what-is-cardiovascular-disease" },
      { label: "U.S. FDA", title: "Microplastics and nanoplastics in foods", href: "https://www.fda.gov/food/environmental-contaminants-food/microplastics-and-nanoplastics-foods" },
      { label: "Say No to Plastic", title: "Our evidence standard", href: "/editorial-policy" },
    ],
  },
  {
    slug: "microplastics-placenta-pregnancy",
    category: "Families",
    title: "Microplastics and the placenta: detection, uncertainty, and precaution",
    description: "How to understand early placental findings without turning an emerging field into a diagnosis.",
    readingTime: "8 minute read",
    takeaway: "Placental detection studies raise important exposure questions. They do not establish that detected particles caused a pregnancy complication or fetal health outcome.",
    known: [
      "Researchers have reported microplastic signals in placental samples.",
      "The placenta is a temporary organ central to fetal development and maternal-fetal exchange.",
      "Early studies were small and required demanding contamination-control procedures.",
      "Research interest has expanded because prenatal development is a sensitive biological period.",
    ],
    uncertain: [
      "Reported presence does not establish dose, timing, transfer, or biological effect.",
      "Small samples cannot estimate prevalence across a population.",
      "Contamination and analytical limitations remain important concerns.",
      "The evidence does not support predicting an individual pregnancy outcome.",
    ],
    actions: [
      "Keep prenatal care, nutrition, medication, and infection-prevention guidance as the priority.",
      "Avoid heating food in plastic when an easy alternative is available.",
      "Use filtered tap water where local water quality and clinical guidance support it.",
      "Reduce high-frequency plastic food contact without attempting an expensive total-home replacement.",
      "Bring individual pregnancy questions to an obstetric professional.",
    ],
    sources: [
      { label: "Environment International", title: "Plasticenta: first evidence of microplastics in human placenta", href: "https://pubmed.ncbi.nlm.nih.gov/33395930/" },
      { label: "American College of Obstetricians and Gynecologists", title: "Toxic chemicals: steps to stay safer before and during pregnancy", href: "https://www.acog.org/womens-health/faqs/toxic-chemicals-steps-to-stay-safer-before-and-during-pregnancy" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
      { label: "Say No to Plastic", title: "Medical information boundary", href: "/medical-disclaimer" },
    ],
  },
  {
    slug: "synthetic-clothing-microfibers",
    category: "Textiles",
    title: "Synthetic clothing and microfibers: change the cycle, not the whole closet",
    description: "A measured guide to shedding, washing, durability, and material choices without wasteful replacement.",
    readingTime: "7 minute read",
    takeaway: "Extending garment life, washing thoughtfully, and choosing durable materials when replacement is already needed can reduce shedding without creating unnecessary waste.",
    known: [
      "Polyester, nylon, acrylic, and related textiles are plastic-based materials.",
      "Fibers can shed during manufacturing, wear, washing, and drying.",
      "Garment construction, fabric type, age, and washing conditions influence shedding.",
      "Microfibers can enter wastewater and indoor dust.",
    ],
    uncertain: [
      "Material labels alone do not predict a garment's total lifetime shedding.",
      "Natural fibers also have environmental impacts and may receive chemical treatments.",
      "Capture devices vary in effectiveness and still require responsible disposal of collected fibers.",
      "Personal exposure reduction from any single laundry change is difficult to quantify.",
    ],
    actions: [
      "Keep serviceable clothing in use instead of replacing an entire wardrobe.",
      "Wash full loads on gentler, cooler cycles when appropriate for hygiene.",
      "Air-dry suitable garments and avoid unnecessary high heat.",
      "Choose durable construction and repairable garments when buying replacements.",
      "Evaluate microfiber-capture products by measured performance and maintenance burden.",
    ],
    sources: [
      { label: "UN Environment Programme", title: "Five ways to reduce waste in the fashion industry", href: "https://www.unep.org/news-and-stories/story/five-ways-reduce-waste-fashion-industry" },
      { label: "European Environment Agency", title: "Microplastics from textiles", href: "https://www.eea.europa.eu/en/analysis/publications/microplastics-from-textiles-towards-a-circular-economy-for-textiles-in-europe" },
      { label: "Environmental Science & Technology", title: "The contribution of washing processes to microfiber release", href: "https://pubs.acs.org/doi/10.1021/acs.est.9b06892" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
    ],
  },
  {
    slug: "food-packaging-takeout-plastic",
    category: "Food",
    title: "Food packaging and takeout: reduce the contact that repeats",
    description: "How heat, oils, acidity, storage time, and processing shape a practical food-contact strategy.",
    readingTime: "8 minute read",
    takeaway: "Prioritize hot, oily, acidic, and frequently consumed foods when reducing plastic contact. Repetition and temperature provide a more useful hierarchy than chasing perfection.",
    known: [
      "Food can contact plastic during processing, packaging, transport, retail, storage, and preparation.",
      "Temperature, contact time, food chemistry, and material condition can influence migration and shedding.",
      "Many metal cans and paper-based packages contain polymer coatings or liners.",
      "Minimally processed food can reduce packaging contact as well as other dietary exposures.",
    ],
    uncertain: [
      "Packaging appearance does not reveal every layer, coating, adhesive, or additive.",
      "A detected particle or chemical does not by itself establish a clinical effect.",
      "Comparisons across studies are difficult when sampling and detection methods differ.",
      "Replacing one material can introduce different environmental, cost, or food-safety tradeoffs.",
    ],
    actions: [
      "Transfer hot takeout food from plastic when a safe reusable dish is available.",
      "Avoid reheating food in disposable packaging.",
      "Favor fresh or minimally processed options when realistic for budget and access.",
      "Choose glass, steel, or ceramic for high-frequency home storage and reheating.",
      "Keep food safety, refrigeration, and allergen controls ahead of packaging concerns.",
    ],
    sources: [
      { label: "U.S. FDA", title: "Food ingredients and packaging", href: "https://www.fda.gov/food/food-ingredients-packaging" },
      { label: "U.S. FDA", title: "Microplastics and nanoplastics in foods", href: "https://www.fda.gov/food/environmental-contaminants-food/microplastics-and-nanoplastics-foods" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
      { label: "National Institute of Environmental Health Sciences", title: "Endocrine disruptors", href: "https://www.niehs.nih.gov/health/topics/agents/endocrine" },
    ],
  },

  {
    slug: "personal-care-cosmetics-plastic",
    category: "Personal care",
    title: "Personal care and cosmetics: read labels without chasing perfection",
    description: "A practical guide to microbead rules, cosmetic labels, packaging, high-frequency products, and claims that deserve a closer look.",
    readingTime: "8 minute read",
    audience: "Everyday routines",
    featured: true,
    publishedDate: "2026-08-06",
    updatedDate: "2026-08-06",
    takeaway: "The U.S. microbead law addressed a narrow group of intentionally added rinse-off particles. A useful routine focuses on products used frequently, avoids vague fear-based claims, and keeps medically important products ahead of packaging concerns.",
    known: [
      "The U.S. Microbead-Free Waters Act prohibits manufacturing, packaging, and distributing rinse-off cosmetics containing plastic microbeads intended to exfoliate or cleanse.",
      "That law is narrower than a ban on every synthetic polymer, cosmetic ingredient, or plastic package.",
      "Products commonly called personal care products can fall under different regulatory categories depending on their intended use and claims.",
      "Cosmetic labels provide ingredient and use information, but they do not describe every packaging material or environmental tradeoff.",
    ],
    uncertain: [
      "An unfamiliar polymer name on an ingredient list does not by itself establish particle exposure or health risk.",
      "Product-level data on microplastic release, absorbed dose, and clinical significance remain limited.",
      "Terms such as natural, clean, green, or non-toxic do not provide a complete safety or environmental assessment.",
      "Replacing a stable product can introduce allergy, irritation, hygiene, cost, or waste tradeoffs.",
    ],
    actions: [
      "Use products safely and finish suitable items before replacing an entire routine.",
      "Avoid rinse-off exfoliating products that advertise plastic beads or glitter-like plastic particles.",
      "Prioritize high-frequency products and lower-packaging or refill options when hygiene and product stability are clear.",
      "Do not stop sunscreen, prescription, acne, or other medically important products solely because of packaging concerns.",
      "Keep labels, lot information, and manufacturer contact details when reporting an adverse reaction.",
    ],
    sources: [
      { label: "U.S. FDA", title: "The Microbead-Free Waters Act: FAQs", href: "https://www.fda.gov/cosmetics/cosmetics-laws-regulations/microbead-free-waters-act-faqs" },
      { label: "U.S. FDA", title: "Cosmetics and U.S. law", href: "https://www.fda.gov/cosmetics/cosmetics-laws-regulations/cosmetics-us-law" },
      { label: "U.S. FDA", title: "Cosmetics labeling regulations", href: "https://www.fda.gov/cosmetics/cosmetics-labeling/cosmetics-labeling-regulations" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
    ],
  },
  {
    slug: "reusable-food-drink-containers",
    category: "Kitchen",
    title: "Reusable food and drink containers: choose by temperature and use",
    description: "How to prioritize glass, stainless steel, ceramic, and existing containers around heat, breakage, food safety, and daily repetition.",
    readingTime: "8 minute read",
    audience: "Kitchen setup",
    featured: true,
    publishedDate: "2026-08-06",
    updatedDate: "2026-08-06",
    takeaway: "Choose containers around the actual job. Heat and repeated food contact deserve the highest priority, while breakage, cleaning, food safety, weight, and access still matter.",
    known: [
      "Food contacts packaging and containers during processing, transport, storage, preparation, and serving.",
      "Temperature, contact time, food chemistry, material condition, and intended use can influence migration or shedding.",
      "Glass, stainless steel, and suitable ceramic can reduce routine plastic contact for many storage and reheating uses.",
      "Food safety, cleaning, refrigeration, and breakage prevention remain more immediate hazards than material optimization in many situations.",
    ],
    uncertain: [
      "A material name alone does not reveal coatings, seals, adhesives, manufacturing quality, or lifetime performance.",
      "No household material is impact-free or ideal for every use.",
      "Laboratory release measurements cannot be converted directly into an individual's absorbed dose or health outcome.",
      "A heavier or breakable alternative may be impractical for children, travel, disability access, or emergency storage.",
    ],
    actions: [
      "Move reheating and very hot food to glass or suitable ceramic first.",
      "Use stainless steel or glass for the drinks and foods handled most often when practical.",
      "Keep serviceable containers for low-heat, non-food, or occasional uses instead of creating unnecessary waste.",
      "Check lids, gaskets, chips, cracks, rust, and manufacturer temperature instructions.",
      "Choose a small repeatable set before buying a large replacement collection.",
    ],
    sources: [
      { label: "U.S. FDA", title: "Food ingredients and packaging", href: "https://www.fda.gov/food/food-ingredients-packaging" },
      { label: "U.S. FDA", title: "Microplastics and nanoplastics in foods", href: "https://www.fda.gov/food/environmental-contaminants-food/microplastics-and-nanoplastics-foods" },
      { label: "U.S. CDC", title: "Food safety basics", href: "https://www.cdc.gov/food-safety/about/index.html" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
    ],
  },
  {
    slug: "children-household-plastic-priorities",
    category: "Families",
    title: "Children and household plastic: a priority order for busy families",
    description: "A calm hierarchy for food contact, heat, floor dust, handwashing, toys, and purchasing decisions without blaming parents.",
    readingTime: "9 minute read",
    audience: "Parents and caregivers",
    featured: true,
    publishedDate: "2026-08-06",
    updatedDate: "2026-08-06",
    takeaway: "Families do not need a plastic-free home. Start with hot food, drinking routines, damaged food-contact items, floor dust, and the products a child uses repeatedly.",
    known: [
      "Children can have more contact with floors and household dust because of play patterns and hand-to-mouth behavior.",
      "Indoor dust contains many particle and chemical sources, not only plastic fibers.",
      "Food-contact materials, heating, cleaning, ventilation, and product condition create practical places to reduce repeated exposure.",
      "Nutrition, safe sleep, medication, injury prevention, food safety, and established pediatric guidance remain higher-priority health protections.",
    ],
    uncertain: [
      "Household particle measurements cannot predict an individual child's retained dose or health outcome.",
      "The relative contribution of one toy, textile, bottle, or furnishing is usually difficult to isolate.",
      "Product labels do not provide a complete lifetime exposure or shedding profile.",
      "Rapid replacement can create cost, waste, stress, and new safety tradeoffs.",
    ],
    actions: [
      "Avoid heating children's food in plastic when a safe alternative is available.",
      "Replace damaged high-frequency food-contact items before low-use objects.",
      "Damp-dust, vacuum with a well-sealed filtered machine, and wash hands before eating.",
      "Keep established infant-feeding, medication, nutrition, and pediatric advice ahead of material concerns.",
      "Choose durable, washable, age-appropriate items when replacement is already needed.",
    ],
    sources: [
      { label: "U.S. EPA", title: "Improving your indoor environment", href: "https://www.epa.gov/indoor-air-quality-iaq/improving-your-indoor-environment" },
      { label: "U.S. EPA", title: "What you can do to protect children from environmental risks", href: "https://www.epa.gov/children/what-you-can-do-protect-children-environmental-risks" },
      { label: "American Academy of Pediatrics", title: "Food additives and child health", href: "https://pubmed.ncbi.nlm.nih.gov/30037972/" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
    ],
  },
  {
    slug: "laundry-microfiber-capture",
    category: "Textiles",
    title: "Laundry microfiber capture: what a device can and cannot solve",
    description: "How to compare filters, bags, balls, wash settings, maintenance, captured lint, and the bigger value of durable clothing.",
    readingTime: "8 minute read",
    audience: "Laundry routines",
    publishedDate: "2026-08-06",
    updatedDate: "2026-08-06",
    takeaway: "Capture devices can be one layer of a laundry strategy, but performance, fit, maintenance, disposal, and garment durability matter. No device makes synthetic clothing shed nothing.",
    known: [
      "Synthetic textiles can release fibers during manufacturing, wear, washing, and drying.",
      "Fabric construction, garment age, wash conditions, and appliance type influence release.",
      "External filters, in-drum devices, and wash bags use different capture mechanisms and cannot be assumed equivalent.",
      "Captured lint and fibers still require disposal and device maintenance.",
    ],
    uncertain: [
      "Product marketing does not always provide comparable test methods, particle-size ranges, or long-term performance.",
      "Laboratory capture percentages may not represent every fabric, machine, detergent, or household cycle.",
      "The exposure reduction for a specific household or wearer is difficult to quantify.",
      "A device's manufacturing, replacement parts, water use, and failure risk can change its overall tradeoff.",
    ],
    actions: [
      "Keep durable garments in use and avoid replacing a functioning wardrobe solely to change fiber type.",
      "Use full loads, gentler cycles, cooler water, and air drying when compatible with hygiene and garment care.",
      "Compare independently described test methods, maintenance frequency, leak risk, and replacement cost before buying a capture device.",
      "Dispose of captured lint in household waste rather than rinsing it down a drain.",
      "Treat capture as one layer alongside buying fewer, longer-lasting garments.",
    ],
    sources: [
      { label: "European Environment Agency", title: "Microplastics from textiles", href: "https://www.eea.europa.eu/en/analysis/publications/microplastics-from-textiles-towards-a-circular-economy-for-textiles-in-europe" },
      { label: "UN Environment Programme", title: "Five ways to reduce waste in the fashion industry", href: "https://www.unep.org/news-and-stories/story/five-ways-reduce-waste-fashion-industry" },
      { label: "Environmental Science & Technology", title: "The contribution of washing processes to microfiber release", href: "https://pubs.acs.org/doi/10.1021/acs.est.9b06892" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
    ],
  },

  {
    slug: "plastic-kitchen-conversion",
    category: "Kitchen",
    title: "A practical plastic-free kitchen conversion",
    description: "A room-by-room checklist for food storage, drinkware, utensils, plates, cups, and the tools used around heat.",
    readingTime: "7 minute read",
    audience: "Kitchen setup",
    featured: true,
    publishedDate: "2026-08-06",
    updatedDate: "2026-08-06",
    takeaway: "Begin with the plastic that touches hot food, drinking water, and the meals you store most often. Replace items as a planned set: storage, drinkware, utensils, and serving pieces—not as an expensive panic purchase.",
    known: [
      "Temperature, contact time, food chemistry, wear, and intended use can influence migration or shedding from food-contact materials.",
      "Glass, suitable ceramic, stainless steel, and appropriate wood products can replace many common plastic kitchen uses.",
      "Food safety, cleaning, breakage, disability access, and safe handling still matter when choosing an alternative.",
      "Replacing the items used around heat and repeated food contact creates a clear priority order.",
    ],
    uncertain: [
      "A material label does not reveal every coating, glaze, seal, adhesive, or manufacturing detail.",
      "No material is ideal for every person, appliance, child, travel need, or emergency use.",
      "Laboratory measurements do not predict an individual's absorbed dose or health outcome.",
      "Replacing safe items all at once can create unnecessary expense and waste.",
    ],
    actions: [
      "Food storage: use glass, ceramic, or stainless steel for the containers used most often.",
      "Heating and serving: use glass, suitable ceramic, stainless steel, cast iron, or another material rated for the job.",
      "Utensils: when plastic spatulas, spoons, cutting tools, or ladles need replacing, choose suitable wood or stainless steel.",
      "Drinkware and tableware: use glass, ceramic, or stainless steel for daily bottles, cups, plates, and bowls when practical.",
      "Buy a small durable set first; confirm lids, glazes, coatings, cleaning instructions, chips, cracks, and heat ratings.",
    ],
    sources: [
      { label: "U.S. FDA", title: "Food ingredients and packaging", href: "https://www.fda.gov/food/food-ingredients-packaging" },
      { label: "U.S. FDA", title: "Microplastics and nanoplastics in foods", href: "https://www.fda.gov/food/environmental-contaminants-food/microplastics-and-nanoplastics-foods" },
      { label: "U.S. CDC", title: "Food safety basics", href: "https://www.cdc.gov/food-safety/about/index.html" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
    ],
  },
  {
    slug: "single-use-plastic-foodware",
    category: "Kitchen",
    title: "Single-use plastic foodware: remove the habit, not just the item",
    description: "A direct plan for disposable cups, plates, utensils, takeout containers, and recurring events or meals.",
    readingTime: "6 minute read",
    audience: "Home, work, and events",
    featured: true,
    publishedDate: "2026-08-06",
    updatedDate: "2026-08-06",
    takeaway: "Eliminate disposable plastic cups, plates, utensils, and food containers where a safe reusable option is practical. Start with the one event, takeout meal, workplace, or household routine that creates the most repeated waste.",
    known: [
      "Single-use foodware creates repeated plastic contact and a large stream of short-lived waste.",
      "Hot food and drinks can add temperature to the food-contact decision.",
      "Reusable systems work best when washing, transport, storage, and return are designed into the routine.",
      "Food safety and accessibility remain essential when choosing a reusable alternative.",
    ],
    uncertain: [
      "The lowest-impact material depends on how often it is reused, how it is washed, and how local waste systems operate.",
      "A label such as compostable or biodegradable does not guarantee that an item will break down in a local facility.",
      "Not every event, disability, emergency, school, or workplace can use the same replacement system.",
      "Material changes alone do not solve overconsumption or poor waste management.",
    ],
    actions: [
      "Stop buying disposable plastic cups, plates, and utensils for routine home use when washable alternatives are available.",
      "Bring a reusable glass, steel, or ceramic option for a recurring takeout, work, school, or event habit when safe and practical.",
      "Ask restaurants not to include plastic utensils or extras you will not use.",
      "Move hot takeout food out of disposable plastic before reheating or long storage.",
      "For gatherings, build a wash-and-return plan instead of replacing one disposable item with another disposable item.",
    ],
    sources: [
      { label: "U.S. FDA", title: "Food ingredients and packaging", href: "https://www.fda.gov/food/food-ingredients-packaging" },
      { label: "U.S. FDA", title: "Microplastics and nanoplastics in foods", href: "https://www.fda.gov/food/environmental-contaminants-food/microplastics-and-nanoplastics-foods" },
      { label: "World Health Organization", title: "Dietary and inhalation exposure to nano- and microplastic particles", href: "https://www.who.int/publications/i/item/9789240054608" },
      { label: "U.S. CDC", title: "Food safety basics", href: "https://www.cdc.gov/food-safety/about/index.html" },
    ],
  },

];

export function getGuide(slug: string) {
  return guides.find((guide) => guide.slug === slug);
}
