import type { EvidenceChapter, EvidenceStudy } from "../evidence";

const blood: EvidenceStudy = {
  id: "blood-study",
  navLabel: "Sangre",
  chapter: "Circulación",
  context: "maternal",
  modelLabel: "Vista de circulación de todo el cuerpo",
  headline: "Se midió plástico en sangre humana.",
  stat: "17 de 22",
  statLabel: "personas tenían plástico detectado en la sangre",
  finding: "Los investigadores detectaron polímeros plásticos en la sangre de 17 de 22 voluntarios sanos. En todas las muestras, la concentración media medida fue de 1,6 microgramos por mililitro.",
  meaning: "El estudio mostró que material derivado del plástico puede entrar en el torrente sanguíneo y circular por el cuerpo.",
  studyType: "Estudio de biomonitoreo humano",
  sample: "22 adultos sanos voluntarios",
  method: "Cromatografía de gases por pirólisis de doble disparo con espectrometría de masas",
  limits: "Este pequeño estudio, uno de los primeros de su tipo, midió masa de polímeros. No determinó los efectos para la salud ni cuánto tiempo permaneció el material en la sangre.",
  year: "2022",
  journal: "Environment International",
  source: "https://pubmed.ncbi.nlm.nih.gov/35367073/",
  doi: "10.1016/j.envint.2022.107199",
};

const brain: EvidenceStudy = {
  id: "brain-study",
  navLabel: "Cerebro",
  chapter: "Cerebro",
  context: "maternal",
  modelLabel: "Cerebro dentro del cráneo",
  headline: "El cerebro contenía mucho más plástico que el hígado o los riñones.",
  stat: "≈50%",
  statLabel: "más en las muestras cerebrales de 2024 que en las de 2016",
  finding: "En muestras post mortem, los investigadores midieron considerablemente más microplásticos y nanoplásticos en tejido cerebral que en hígado o riñón. Las concentraciones cerebrales medidas también fueron aproximadamente un 50% mayores en las muestras de 2024 que en las de 2016.",
  meaning: "El hallazgo muestra que las partículas de plástico más pequeñas pueden llegar al cerebro, un órgano protegido por la barrera hematoencefálica.",
  studyType: "Estudio post mortem de tejido humano",
  sample: "52 muestras de corteza frontal: 28 recogidas en 2016 y 24 en 2024, con comparaciones de hígado y riñón y cohortes históricas y de demencia separadas",
  method: "Cromatografía de gases por pirólisis con espectrometría de masas, apoyada por microscopía",
  limits: "La investigación post mortem puede mostrar dónde estaba presente el material, no qué síntomas causó. Los niveles más altos en muestras de personas con demencia no demuestran que el plástico causara demencia.",
  year: "2025",
  journal: "Nature Medicine",
  source: "https://www.nature.com/articles/s41591-024-03453-1",
  doi: "10.1038/s41591-024-03453-1",
};

const heartAttack: EvidenceStudy = {
  id: "acute-heart-attack-study",
  navLabel: "Infarto",
  chapter: "Corazón y arterias",
  context: "maternal",
  modelLabel: "Corazón dentro del tórax",
  headline: "El plástico se detectó con mayor frecuencia en personas tratadas por un infarto agudo.",
  stat: "16 de 19",
  statLabel: "pacientes con infarto agudo tenían partículas detectadas",
  finding: "El estudio detectó microplásticos y nanoplásticos en 16 de 19 pacientes con infarto agudo (84,2%), frente a 8 de 20 personas con síndrome coronario crónico y 7 de 22 controles con arterias coronarias normales.",
  meaning: "El grupo con infarto agudo presentó las mayores concentraciones y la mayor variedad de polímeros, con los niveles más altos en sangre obtenida de la circulación coronaria alrededor del corazón.",
  studyType: "Estudio transversal de sangre coronaria",
  sample: "61 personas sometidas a angiografía coronaria: 19 con infarto agudo, 20 con síndrome coronario crónico y 22 controles",
  method: "Cromatografía de gases por pirólisis con espectrometría de masas y espectroscopia infrarroja directa por láser",
  limits: "Este estudio encontró una asociación fuerte en un único momento. No puede determinar si el plástico contribuyó al infarto. El tabaquismo fue el único predictor independiente en el análisis ajustado de los autores.",
  year: "2026",
  journal: "European Heart Journal",
  source: "https://academic.oup.com/eurheartj/advance-article/doi/10.1093/eurheartj/ehag447/8725569",
  doi: "10.1093/eurheartj/ehag447",
};

const plaque: EvidenceStudy = {
  id: "artery-plaque-study",
  navLabel: "Placa arterial",
  chapter: "Corazón y arterias",
  context: "maternal",
  modelLabel: "Arterias · placa extraída durante cirugía",
  headline: "El plástico en la placa arterial se asoció con más infartos, accidentes cerebrovasculares y muertes.",
  stat: "4,53×",
  statLabel: "mayor riesgo combinado durante el seguimiento",
  finding: "Entre 257 personas seguidas después de una cirugía para retirar placa de la arteria carótida, se detectó polietileno en la placa de 150 personas y PVC en 31. Quienes tenían microplásticos o nanoplásticos en la placa presentaron una mayor tasa de infarto, accidente cerebrovascular o muerte por cualquier causa durante unos 34 meses de seguimiento.",
  meaning: "Fue uno de los primeros grandes estudios humanos que relacionó plástico encontrado dentro de arterias enfermas con resultados cardiovasculares posteriores.",
  studyType: "Estudio observacional prospectivo",
  sample: "257 personas que completaron el seguimiento después de una endarterectomía carotídea",
  method: "Cromatografía de gases por pirólisis con espectrometría de masas, análisis de isótopos estables y microscopía electrónica",
  limits: "El estudio fue observacional. Encontró una asociación después del ajuste estadístico, pero no demostró que el plástico de la placa causara los eventos posteriores.",
  year: "2024",
  journal: "The New England Journal of Medicine",
  source: "https://pubmed.ncbi.nlm.nih.gov/38446676/",
  doi: "10.1056/NEJMoa2309822",
};

const pregnancy: EvidenceStudy = {
  id: "pregnancy-context",
  navLabel: "Embarazo",
  chapter: "Embarazo",
  context: "maternal",
  modelLabel: "Cuerpo durante el embarazo, feto, placenta y amnios",
  modelNote: "La madre y el feto tienen circulaciones separadas conectadas a través de la placenta y el cordón umbilical.",
  headline: "La placenta es la superficie de intercambio entre la madre y el bebé en desarrollo.",
  stat: "Dos",
  statLabel: "circulaciones separadas conectadas por la placenta",
  finding: "La sangre materna lleva oxígeno y nutrientes a la placenta. El feto los recibe a través de su propia circulación y del cordón umbilical, mientras el dióxido de carbono y otros residuos regresan a través de la placenta.",
  meaning: "Esto hace de la placenta un lugar especialmente importante para investigar exposiciones ambientales durante el embarazo.",
  studyType: "Contexto anatómico",
  sample: "Circulación materna, placenta, cordón umbilical y circulación fetal",
  method: "Anatomía y fisiología humanas establecidas",
  limits: "Este capítulo explica la vía biológica. El estudio de placenta humana que aparece a continuación establece detección en tejido; por sí solo no demuestra un efecto sobre el embarazo o el bebé.",
  year: "Anatomía actual",
  journal: "NIH Human Reference Atlas",
  source: "https://3d.nih.gov/collections/hra",
};

const placenta: EvidenceStudy = {
  id: "placenta-study",
  navLabel: "Placenta",
  chapter: "Placenta",
  context: "maternal",
  modelLabel: "Placenta y vasos umbilicales",
  headline: "Se encontraron partículas fabricadas por el ser humano en ambos lados de la placenta.",
  stat: "4 de 6",
  statLabel: "placentas contenían micropartículas pigmentadas",
  finding: "Los investigadores encontraron 12 micropartículas pigmentadas en cuatro placentas: cinco en tejido del lado fetal, cuatro en tejido del lado materno y tres en las membranas que rodean al feto. Tres fueron identificadas como polipropileno; las demás coincidían con pigmentos o recubrimientos fabricados por el ser humano.",
  meaning: "Las partículas no estaban confinadas a una sola superficie externa. Llegaron a tejidos que apoyan el intercambio entre la madre y el bebé en desarrollo.",
  studyType: "Estudio exploratorio de tejido humano",
  sample: "Seis placentas recogidas después del parto",
  method: "Microespectroscopia Raman con un protocolo de recolección sin plástico",
  limits: "Fue un estudio de detección muy pequeño y solo tres partículas se confirmaron químicamente como polímero plástico. No midió complicaciones del embarazo, desarrollo fetal ni la salud de los niños.",
  year: "2021",
  journal: "Environment International",
  source: "https://pubmed.ncbi.nlm.nih.gov/33395930/",
  doi: "10.1016/j.envint.2020.106274",
};

const ovary: EvidenceStudy = {
  id: "follicular-fluid-study",
  navLabel: "Ovario",
  chapter: "Ovario y óvulos en desarrollo",
  context: "maternal",
  modelLabel: "Ovario completo · los óvulos se desarrollan dentro de folículos microscópicos",
  modelNote: "El líquido folicular es el líquido que rodea y apoya directamente a un óvulo en desarrollo dentro del ovario.",
  headline: "Se encontró plástico en el líquido que rodea a óvulos humanos en desarrollo.",
  stat: "14 de 18",
  statLabel: "muestras de líquido folicular tenían partículas detectadas",
  finding: "Los investigadores detectaron microplásticos en 14 de 18 muestras de líquido folicular de mujeres sometidas a reproducción asistida. La concentración media reportada fue de 2.191 partículas por mililitro.",
  meaning: "El líquido folicular rodea y apoya directamente a un óvulo en desarrollo. El hallazgo muestra que la exposición al plástico alcanzó ese entorno reproductivo.",
  studyType: "Estudio humano de líquido folicular",
  sample: "18 mujeres sometidas a reproducción asistida",
  method: "Microscopía electrónica de barrido con espectroscopia de rayos X de energía dispersiva",
  limits: "El estudio fue pequeño. En este grupo, los investigadores no encontraron asociación con fertilización, aborto espontáneo o nacimiento vivo, por lo que no puede establecer un efecto sobre la fertilidad humana.",
  year: "2025",
  journal: "Ecotoxicology and Environmental Safety",
  source: "https://pubmed.ncbi.nlm.nih.gov/39947063/",
  doi: "10.1016/j.ecoenv.2025.117868",
};

const testicular: EvidenceStudy = {
  id: "testicular-tissue-study",
  navLabel: "Tejido testicular",
  chapter: "Tejido testicular",
  context: "male",
  modelLabel: "Muestra reproductiva masculina separada",
  modelNote: "Esta evidencia procede de un contexto anatómico masculino separado; no forma parte del modelo materno.",
  headline: "Se encontró masa de polímeros plásticos en todas las muestras humanas de testículo.",
  stat: "23 de 23",
  statLabel: "muestras humanas tenían masa de polímeros plásticos detectada",
  finding: "Se midió masa de polímeros derivados del plástico en las 23 muestras humanas archivadas de testículo. La cantidad media medida en tejido humano fue de 328,44 microgramos por gramo, aproximadamente 2,7 veces la media de las muestras caninas estudiadas junto con ellas.",
  meaning: "El resultado confirma que los microplásticos pueden alcanzar tejido reproductivo masculino. En los perros, niveles mayores de algunos polímeros se asociaron con menor peso testicular, lo que plantea preguntas para futuras investigaciones sobre fertilidad.",
  studyType: "Estudio de tejido entre especies",
  sample: "23 muestras humanas archivadas de testículo y 47 muestras caninas",
  method: "Cromatografía de gases por pirólisis con espectrometría de masas",
  limits: "Las muestras humanas archivadas no incluían mediciones de esperma, por lo que el estudio no pudo evaluar la fertilidad humana. La asociación con el peso testicular se encontró en perros, no en personas.",
  year: "2024",
  journal: "Toxicological Sciences",
  source: "https://academic.oup.com/toxsci/article/200/2/235/7673133",
  doi: "10.1093/toxsci/kfae060",
};

export const evidenceChaptersEs: EvidenceChapter[] = [
  { id: "blood", navLabel: "Sangre", title: "Torrente sanguíneo", eyebrow: "Cómo se mueve el plástico", studies: [blood] },
  { id: "brain", navLabel: "Cerebro", title: "Tejido cerebral", eyebrow: "A través de una barrera protectora", studies: [brain] },
  { id: "heart-arteries", navLabel: "Corazón y arterias", title: "Corazón y arterias", eyebrow: "Dos señales cardiovasculares", introduction: "Un estudio examinó plástico en sangre coronaria durante un infarto. Otro siguió a personas después de encontrar plástico dentro de placa arterial.", studies: [heartAttack, plaque] },
  { id: "pregnancy", navLabel: "Embarazo", title: "Embarazo", eyebrow: "Cómo se conectan madre y bebé", studies: [pregnancy] },
  { id: "placenta", navLabel: "Placenta", title: "Placenta", eyebrow: "En la superficie de intercambio", studies: [placenta] },
  { id: "ovary", navLabel: "Ovario y óvulos", title: "Ovario y óvulos en desarrollo", eyebrow: "El líquido alrededor de un óvulo", studies: [ovary] },
  { id: "testicular-tissue", navLabel: "Tejido testicular", title: "Tejido testicular", eyebrow: "Un estudio masculino separado", studies: [testicular] },
];

export const evidenceStudiesEs = evidenceChaptersEs.flatMap((chapter) => chapter.studies);
