import type { EvidenceChapter, EvidenceStudy, HomepageJourneyChapter } from "../evidence";

const blood: EvidenceStudy = {
  id: "blood-study",
  navLabel: "Sangre",
  chapter: "Circulación",
  context: "maternal",
  modelLabel: "Vista de circulación de todo el cuerpo",
  headline: "Se midió plástico en sangre humana.",
  stat: "17 de 22",
  statLabel: "personas tenían plástico detectado en la sangre",
  finding: "Los investigadores detectaron polímeros plásticos en la sangre de 17 de 22 voluntarios sanos. En todas las muestras, la concentración media medida fue de 1,6 microgramos por mililitro.",
  meaning: "El estudio mostró que material derivado del plástico puede entrar en el torrente sanguíneo y circular por el cuerpo.",
  studyType: "Estudio de biomonitoreo humano",
  sample: "22 adultos sanos voluntarios",
  method: "Cromatografía de gases por pirólisis de doble disparo con espectrometría de masas",
  limits: "Este pequeño estudio, uno de los primeros de su tipo, midió masa de polímeros. No determinó los efectos para la salud ni cuánto tiempo permaneció el material en la sangre.",
  year: "2022",
  journal: "Environment International",
  source: "https://pubmed.ncbi.nlm.nih.gov/35367073/",
  doi: "10.1016/j.envint.2022.107199",
};

const brain: EvidenceStudy = {
  id: "brain-study",
  navLabel: "Cerebro",
  chapter: "Cerebro",
  context: "maternal",
  modelLabel: "Cerebro dentro del cráneo",
  headline: "El cerebro contenía mucho más plástico que el hígado o los riñones.",
  stat: "≈50%",
  statLabel: "más en las muestras cerebrales de 2024 que en las de 2016",
  finding: "En muestras post mortem, los investigadores midieron considerablemente más microplásticos y nanoplásticos en tejido cerebral que en hígado o riñón. Las concentraciones cerebrales medidas también fueron aproximadamente un 50% mayores en las muestras de 2024 que en las de 2016.",
  meaning: "El hallazgo muestra que las partículas de plástico más pequeñas pueden llegar al cerebro, un órgano protegido por la barrera hematoencefálica.",
  studyType: "Estudio post mortem de tejido humano",
  sample: "52 muestras de corteza frontal: 28 recogidas en 2016 y 24 en 2024, con comparaciones de hígado y riñón y cohortes históricas y de demencia separadas",
  method: "Cromatografía de gases por pirólisis con espectrometría de masas, apoyada por microscopía",
  limits: "La investigación post mortem puede mostrar dónde estaba presente el material, no qué síntomas causó. Los niveles más altos en muestras de personas con demencia no demuestran que el plástico causara demencia.",
  year: "2025",
  journal: "Nature Medicine",
  source: "https://www.nature.com/articles/s41591-024-03453-1",
  doi: "10.1038/s41591-024-03453-1",
};

const heartAttack: EvidenceStudy = {
  id: "acute-heart-attack-study",
  navLabel: "Infarto",
  chapter: "Corazón y arterias",
  context: "maternal",
  modelLabel: "Corazón dentro del tórax",
  headline: "El plástico se detectó con mayor frecuencia en personas tratadas por un infarto agudo.",
  stat: "16 de 19",
  statLabel: "pacientes con infarto agudo tenían partículas detectadas",
  finding: "El estudio detectó microplásticos y nanoplásticos en 16 de 19 pacientes con infarto agudo (84,2%), frente a 8 de 20 personas con síndrome coronario crónico y 7 de 22 controles con arterias coronarias normales.",
  meaning: "El grupo con infarto agudo presentó las mayores concentraciones y la mayor variedad de polímeros, con los niveles más altos en sangre obtenida de la circulación coronaria alrededor del corazón.",
  studyType: "Estudio transversal de sangre coronaria",
  sample: "61 personas sometidas a angiografía coronaria: 19 con infarto agudo, 20 con síndrome coronario crónico y 22 controles",
  method: "Cromatografía de gases por pirólisis con espectrometría de masas y espectroscopia infrarroja directa por láser",
  limits: "Este estudio encontró una asociación fuerte en un único momento. No puede determinar si el plástico contribuyó al infarto. El tabaquismo fue el único predictor independiente en el análisis ajustado de los autores.",
  year: "2026",
  journal: "European Heart Journal",
  source: "https://academic.oup.com/eurheartj/advance-article/doi/10.1093/eurheartj/ehag447/8725569",
  doi: "10.1093/eurheartj/ehag447",
};

const plaque: EvidenceStudy = {
  id: "artery-plaque-study",
  navLabel: "Placa arterial",
  chapter: "Corazón y arterias",
  context: "maternal",
  modelLabel: "Arterias · placa extraída durante cirugía",
  headline: "El plástico en la placa arterial se asoció con más infartos, accidentes cerebrovasculares y muertes.",
  stat: "4,53×",
  statLabel: "mayor riesgo combinado durante el seguimiento",
  finding: "Entre 257 personas seguidas después de una cirugía para retirar placa de la arteria carótida, se detectó polietileno en la placa de 150 personas y PVC en 31. Quienes tenían microplásticos o nanoplásticos en la placa presentaron una mayor tasa de infarto, accidente cerebrovascular o muerte por cualquier causa durante unos 34 meses de seguimiento.",
  meaning: "Fue uno de los primeros grandes estudios humanos que relacionó plástico encontrado dentro de arterias enfermas con resultados cardiovasculares posteriores.",
  studyType: "Estudio observacional prospectivo",
  sample: "257 personas que completaron el seguimiento después de una endarterectomía carotídea",
  method: "Cromatografía de gases por pirólisis con espectrometría de masas, análisis de isótopos estables y microscopía electrónica",
  limits: "El estudio fue observacional. Encontró una asociación después del ajuste estadístico, pero no demostró que el plástico de la placa causara los eventos posteriores.",
  year: "2024",
  journal: "The New England Journal of Medicine",
  source: "https://pubmed.ncbi.nlm.nih.gov/38446676/",
  doi: "10.1056/NEJMoa2309822",
};

const pregnancy: EvidenceStudy = {
  id: "pregnancy-context",
  navLabel: "Embarazo",
  chapter: "Embarazo",
  context: "maternal",
  modelLabel: "Cuerpo durante el embarazo, feto, placenta y amnios",
  modelNote: "La madre y el feto tienen circulaciones separadas conectadas a través de la placenta y el cordón umbilical.",
  headline: "La placenta es la superficie de intercambio entre la madre y el bebé en desarrollo.",
  stat: "Dos",
  statLabel: "circulaciones separadas conectadas por la placenta",
  finding: "La sangre materna lleva oxígeno y nutrientes a la placenta. El feto los recibe a través de su propia circulación y del cordón umbilical, mientras el dióxido de carbono y otros residuos regresan a través de la placenta.",
  meaning: "Esto hace de la placenta un lugar especialmente importante para investigar exposiciones ambientales durante el embarazo.",
  studyType: "Contexto anatómico",
  sample: "Circulación materna, placenta, cordón umbilical y circulación fetal",
  method: "Anatomía y fisiología humanas establecidas",
  limits: "Este capítulo explica la vía biológica. El estudio de placenta humana que aparece a continuación establece detección en tejido; por sí solo no demuestra un efecto sobre el embarazo o el bebé.",
  year: "Anatomía actual",
  journal: "NIH Human Reference Atlas",
  source: "https://3d.nih.gov/collections/hra",
};

const placenta: EvidenceStudy = {
  id: "placenta-study",
  navLabel: "Placenta",
  chapter: "Placenta",
  context: "maternal",
  modelLabel: "Placenta y vasos umbilicales",
  headline: "Se encontraron partículas fabricadas por el ser humano en ambos lados de la placenta.",
  stat: "4 de 6",
  statLabel: "placentas contenían micropartículas pigmentadas",
  finding: "Los investigadores encontraron 12 micropartículas pigmentadas en cuatro placentas: cinco en tejido del lado fetal, cuatro en tejido del lado materno y tres en las membranas que rodean al feto. Tres fueron identificadas como polipropileno; las demás coincidían con pigmentos o recubrimientos fabricados por el ser humano.",
  meaning: "Las partículas no estaban confinadas a una sola superficie externa. Llegaron a tejidos que apoyan el intercambio entre la madre y el bebé en desarrollo.",
  studyType: "Estudio exploratorio de tejido humano",
  sample: "Seis placentas recogidas después del parto",
  method: "Microespectroscopia Raman con un protocolo de recolección sin plástico",
  limits: "Fue un estudio de detección muy pequeño y solo tres partículas se confirmaron químicamente como polímero plástico. No midió complicaciones del embarazo, desarrollo fetal ni la salud de los niños.",
  year: "2021",
  journal: "Environment International",
  source: "https://pubmed.ncbi.nlm.nih.gov/33395930/",
  doi: "10.1016/j.envint.2020.106274",
};

const ovary: EvidenceStudy = {
  id: "follicular-fluid-study",
  navLabel: "Ovario",
  chapter: "Ovario y óvulos en desarrollo",
  context: "maternal",
  modelLabel: "Ovario completo · los óvulos se desarrollan dentro de folículos microscópicos",
  modelNote: "El líquido folicular es el líquido que rodea y apoya directamente a un óvulo en desarrollo dentro del ovario.",
  headline: "Se encontró plástico en el líquido que rodea a óvulos humanos en desarrollo.",
  stat: "14 de 18",
  statLabel: "muestras de líquido folicular tenían partículas detectadas",
  finding: "Los investigadores detectaron microplásticos en 14 de 18 muestras de líquido folicular de mujeres sometidas a reproducción asistida. La concentración media reportada fue de 2.191 partículas por mililitro.",
  meaning: "El líquido folicular rodea y apoya directamente a un óvulo en desarrollo. El hallazgo muestra que la exposición al plástico alcanzó ese entorno reproductivo.",
  studyType: "Estudio humano de líquido folicular",
  sample: "18 mujeres sometidas a reproducción asistida",
  method: "Microscopía electrónica de barrido con espectroscopia de rayos X de energía dispersiva",
  limits: "El estudio fue pequeño. En este grupo, los investigadores no encontraron asociación con fertilización, aborto espontáneo o nacimiento vivo, por lo que no puede establecer un efecto sobre la fertilidad humana.",
  year: "2025",
  journal: "Ecotoxicology and Environmental Safety",
  source: "https://pubmed.ncbi.nlm.nih.gov/39947063/",
  doi: "10.1016/j.ecoenv.2025.117868",
};

const testicular: EvidenceStudy = {
  id: "testicular-tissue-study",
  navLabel: "Tejido testicular",
  chapter: "Tejido testicular",
  context: "male",
  modelLabel: "Muestra reproductiva masculina separada",
  modelNote: "Esta evidencia procede de un contexto anatómico masculino separado; no forma parte del modelo materno.",
  headline: "Se encontró masa de polímeros plásticos en todas las muestras humanas de testículo.",
  stat: "23 de 23",
  statLabel: "muestras humanas tenían masa de polímeros plásticos detectada",
  finding: "Se midió masa de polímeros derivados del plástico en las 23 muestras humanas archivadas de testículo. La cantidad media medida en tejido humano fue de 328,44 microgramos por gramo, aproximadamente 2,7 veces la media de las muestras caninas estudiadas junto con ellas.",
  meaning: "El resultado confirma que los microplásticos pueden alcanzar tejido reproductivo masculino. En los perros, niveles mayores de algunos polímeros se asociaron con menor peso testicular, lo que plantea preguntas para futuras investigaciones sobre fertilidad.",
  studyType: "Estudio de tejido entre especies",
  sample: "23 muestras humanas archivadas de testículo y 47 muestras caninas",
  method: "Cromatografía de gases por pirólisis con espectrometría de masas",
  limits: "Las muestras humanas archivadas no incluían mediciones de esperma, por lo que el estudio no pudo evaluar la fertilidad humana. La asociación con el peso testicular se encontró en perros, no en personas.",
  year: "2024",
  journal: "Toxicological Sciences",
  source: "https://academic.oup.com/toxsci/article/200/2/235/7673133",
  doi: "10.1093/toxsci/kfae060",
};

export const evidenceChaptersEs: EvidenceChapter[] = [
  { id: "blood", navLabel: "Sangre", title: "Torrente sanguíneo", eyebrow: "Cómo se mueve el plástico", studies: [blood] },
  { id: "brain", navLabel: "Cerebro", title: "Tejido cerebral", eyebrow: "A través de una barrera protectora", studies: [brain] },
  { id: "heart-arteries", navLabel: "Corazón y arterias", title: "Corazón y arterias", eyebrow: "Dos señales cardiovasculares", introduction: "Un estudio examinó plástico en sangre coronaria durante un infarto. Otro siguió a personas después de encontrar plástico dentro de placa arterial.", studies: [heartAttack, plaque] },
  { id: "pregnancy", navLabel: "Embarazo", title: "Embarazo", eyebrow: "Cómo se conectan madre y bebé", studies: [pregnancy] },
  { id: "placenta", navLabel: "Placenta", title: "Placenta", eyebrow: "En la superficie de intercambio", studies: [placenta] },
  { id: "ovary", navLabel: "Ovario y óvulos", title: "Ovario y óvulos en desarrollo", eyebrow: "El líquido alrededor de un óvulo", studies: [ovary] },
  { id: "testicular-tissue", navLabel: "Tejido testicular", title: "Tejido testicular", eyebrow: "Un estudio masculino separado", studies: [testicular] },
];

export const evidenceStudiesEs = evidenceChaptersEs.flatMap((chapter) => chapter.studies);


export const homepageJourneyEs: HomepageJourneyChapter[] = [
  {
    slug: "blood",
    chapter: "Cuerpo completo y circulación",
    context: blood.context,
    modelLabel: blood.modelLabel,
    modelNote: blood.modelNote,
    title: "Se midió material derivado del plástico en sangre humana.",
    stat: blood.stat,
    statLabel: blood.statLabel,
    finding: "Se detectaron polímeros plásticos en la sangre de 17 de 22 voluntarios sanos.",
    meaning: "Esto muestra que material derivado del plástico puede circular en la sangre. El estudio no evaluó efectos para la salud.",
    compactFinding: "Se detectaron polímeros plásticos en 17 de 22 voluntarios.",
    compactMeaning: "La presencia en sangre no demuestra un efecto sobre la salud.",
    details: `${blood.sample}. ${blood.limits}`,
    sources: [{ label: "Estudio original de sangre", meta: `${blood.journal}, ${blood.year}`, href: blood.source }],
  },
  {
    slug: "brain",
    chapter: "Cerebro",
    context: brain.context,
    modelLabel: brain.modelLabel,
    modelNote: brain.modelNote,
    title: "Se midió material derivado del plástico en tejido cerebral.",
    stat: brain.stat,
    statLabel: brain.statLabel,
    finding: "Las muestras cerebrales contenían más material derivado del plástico que las de hígado o riñón, y los niveles de 2024 fueron aproximadamente un 50% mayores que los de 2016.",
    meaning: "Las partículas más pequeñas pueden llegar al cerebro. Este estudio no mostró qué síntomas causan.",
    compactFinding: "Las muestras cerebrales contenían más material derivado del plástico que las de hígado o riñón.",
    compactMeaning: "El estudio no identificó síntomas ni demostró enfermedad.",
    details: `${brain.sample}. ${brain.limits}`,
    sources: [{ label: "Estudio original de tejido cerebral", meta: `${brain.journal}, ${brain.year}`, href: brain.source }],
  },
  {
    slug: "heart-arteries",
    chapter: "Corazón y arterias",
    context: heartAttack.context,
    modelLabel: "Corazón y circulación coronaria dentro del tórax de referencia",
    modelNote: "Los estudios de sangre coronaria y placa carotídea plantearon preguntas diferentes y se mantienen como registros de evidencia separados.",
    title: "Las partículas se detectaron con mayor frecuencia durante un infarto agudo.",
    stat: heartAttack.stat,
    statLabel: heartAttack.statLabel,
    finding: "Se detectaron partículas en 16 de 19 pacientes con infarto, frente a tasas menores en dos grupos de comparación.",
    meaning: "La asociación es importante, pero no demuestra que el plástico causara el infarto.",
    compactFinding: "Las partículas se detectaron con mayor frecuencia en el grupo con infarto.",
    compactMeaning: "El estudio encontró una asociación, no causalidad.",
    details: `${heartAttack.sample}. ${heartAttack.limits}`,
    sources: [
      { label: "Estudio original de sangre coronaria", meta: `${heartAttack.journal}, ${heartAttack.year}`, href: heartAttack.source },
      { label: "Estudio original de placa arterial", meta: `${plaque.journal}, ${plaque.year}`, href: plaque.source },
    ],
    relatedFinding: {
      eyebrow: "Evidencia relacionada de placa arterial",
      stat: plaque.stat,
      statLabel: plaque.statLabel,
      title: "El plástico en la placa se asoció con más eventos cardiovasculares durante el seguimiento.",
      text: "El estudio de 2024 fue observacional y no demostró causalidad.",
    },
  },
  {
    slug: "pregnancy-placenta",
    chapter: "Embarazo y placenta",
    context: placenta.context,
    modelLabel: "Torso materno, útero, feto, conexión umbilical y placenta",
    modelNote: pregnancy.modelNote,
    title: "Se encontraron partículas en ambos lados de la placenta.",
    stat: placenta.stat,
    statLabel: placenta.statLabel,
    finding: "Los investigadores encontraron 12 partículas pigmentadas en cuatro de seis placentas.",
    meaning: "Las partículas llegaron a tejido del lado materno y fetal. El estudio no evaluó resultados del embarazo.",
    compactFinding: "Se encontraron doce partículas pigmentadas en cuatro placentas.",
    compactMeaning: "El pequeño estudio no midió resultados del embarazo.",
    details: `${placenta.sample}. ${placenta.limits}`,
    sources: [
      { label: "Referencia de anatomía humana", meta: pregnancy.journal, href: pregnancy.source },
      { label: "Estudio original de placenta", meta: `${placenta.journal}, ${placenta.year}`, href: placenta.source },
    ],
  },
  {
    slug: "follicular-fluid",
    chapter: "Ovario y óvulos en desarrollo",
    context: ovary.context,
    modelLabel: ovary.modelLabel,
    modelNote: ovary.modelNote,
    title: "Se encontraron partículas en el líquido que rodea a óvulos en desarrollo.",
    stat: ovary.stat,
    statLabel: ovary.statLabel,
    finding: "Se detectaron microplásticos en 14 de 18 muestras de líquido folicular.",
    meaning: "La exposición llegó al entorno inmediato alrededor de óvulos en desarrollo. Los efectos sobre la fertilidad siguen siendo desconocidos.",
    compactFinding: "Se detectaron partículas en 14 de 18 muestras de líquido folicular.",
    compactMeaning: "El estudio no estableció un efecto sobre la fertilidad.",
    details: `${ovary.sample}. ${ovary.limits}`,
    sources: [{ label: "Estudio original de líquido folicular", meta: `${ovary.journal}, ${ovary.year}`, href: ovary.source }],
  },
  {
    slug: "endocrine-metabolic-system",
    chapter: "Sistema endocrino y metabólico",
    context: "maternal",
    modelLabel: "Tejidos seleccionados que producen hormonas dentro del contexto corporal",
    modelNote: "La escena visible incluye páncreas, timo y ovarios. No inventa tejidos endocrinos que no estén representados.",
    title: "Cuatro tejidos representados que producen hormonas entran en vista.",
    stat: "4 tejidos",
    statLabel: "páncreas, timo y ambos ovarios en esta referencia",
    finding: "Las sustancias químicas asociadas al plástico, como BPA y ftalatos, tienen una base de evidencia endocrina más amplia que las propias partículas microplásticas.",
    meaning: "Todavía se estudia si las partículas microplásticas alteran directamente la señalización hormonal humana.",
    compactFinding: "Las sustancias químicas asociadas al plástico tienen una base de evidencia endocrina más sólida.",
    compactMeaning: "Los efectos directos de las partículas sobre las hormonas humanas siguen siendo inciertos.",
    details: "El sistema endocrino incluye tiroides, páncreas, glándulas suprarrenales, ovarios, testículos y otros tejidos. La revisión proporcionada distingue los aditivos químicos de las partículas plásticas y permanece en revisión de fuentes.",
    sources: [{ label: "Resumen endocrino completo", meta: "Revisión de fuentes del Dr. Haddad", href: "/es/ciencia/cuerpo/endocrine-metabolic-system" }],
  },
  {
    slug: "kidneys-urinary-system",
    chapter: "Riñones y sistema urinario",
    context: "maternal",
    modelLabel: "Riñones, uréteres y vejiga dentro del cuerpo",
    title: "Cinco estructuras urinarias forman una vía conectada.",
    stat: "5 estructuras",
    statLabel: "dos riñones, dos uréteres y la vejiga urinaria",
    finding: "La revisión proporcionada informa detección en tejido renal humano donado, mientras la cita primaria sigue en revisión.",
    meaning: "La detección mostraría que la exposición llegó a un órgano filtrante. No demostraría enfermedad renal.",
    compactFinding: "Se han reportado partículas en tejido renal humano donado.",
    compactMeaning: "Se desconoce cuánto se elimina, cuánto permanece y si afecta la función renal.",
    details: "Los investigadores estudian si las partículas atraviesan los riñones, se eliminan o permanecen en el tejido renal. La evidencia humana sobre resultados clínicos sigue siendo limitada.",
    sources: [{ label: "Resumen completo de riñones", meta: "Resumen de sistema corporal", href: "/es/ciencia/cuerpo/kidneys-urinary-system" }],
  },
  {
    slug: "skin",
    chapter: "Piel y superficie exterior",
    context: "maternal",
    modelLabel: "Superficie exterior completa del cuerpo de referencia femenino",
    title: "La superficie exterior se convierte en la anatomía principal.",
    stat: "1 superficie",
    statLabel: "el cuerpo exterior femenino completo de referencia",
    finding: "La mayoría de las partículas microplásticas son demasiado grandes para atravesar piel sana e intacta.",
    meaning: "Los investigadores todavía estudian nanoplásticos, piel dañada y sustancias químicas asociadas al plástico en productos de cuidado personal.",
    compactFinding: "La piel sana e intacta parece bloquear la mayoría de las partículas microplásticas.",
    compactMeaning: "Los nanoplásticos y la exposición a través de piel dañada siguen siendo preguntas abiertas.",
    details: "La evidencia actual sugiere que inhalación e ingestión siguen siendo las principales vías de exposición. La investigación sobre la piel todavía está en desarrollo.",
    sources: [{ label: "Resumen completo de la piel", meta: "Resumen de sistema corporal", href: "/es/ciencia/cuerpo/skin" }],
  },
  {
    slug: "digestive-system",
    chapter: "Sistema digestivo",
    context: "maternal",
    modelLabel: "Intestinos, hígado y páncreas en contexto corporal",
    title: "Cuatro órganos digestivos aparecen en contexto corporal.",
    stat: "4 órganos",
    statLabel: "intestino delgado y grueso, hígado y páncreas",
    finding: "Se han detectado microplásticos en heces, lo que confirma que partículas ingeridas pasan por el sistema digestivo.",
    meaning: "La mayoría parece eliminarse. Los efectos humanos sobre la barrera intestinal, la inflamación y el microbioma siguen siendo inciertos.",
    compactFinding: "Las partículas ingeridas pasan de forma rutinaria por el tracto digestivo.",
    compactMeaning: "Los efectos humanos sobre la barrera intestinal y el microbioma siguen siendo inciertos.",
    details: "Las partículas muy pequeñas pueden cruzar la barrera intestinal, pero gran parte de esa evidencia proviene de estudios de laboratorio y animales. No se han establecido vínculos directos con enfermedad digestiva.",
    sources: [{ label: "Resumen digestivo completo", meta: "Resumen de sistema corporal", href: "/es/ciencia/cuerpo/digestive-system" }],
  },
  {
    slug: "testicular-tissue",
    chapter: "Tejido testicular",
    context: testicular.context,
    modelLabel: testicular.modelLabel,
    modelNote: testicular.modelNote,
    title: "Se midió masa de polímeros derivados del plástico en tejido testicular.",
    stat: testicular.stat,
    statLabel: testicular.statLabel,
    finding: "Se midió masa de polímeros en las 23 muestras humanas archivadas de testículo.",
    meaning: "El hallazgo confirma presencia en tejido. El estudio no pudo evaluar la fertilidad humana.",
    compactFinding: "Se midió masa de polímeros en las 23 muestras humanas archivadas.",
    compactMeaning: "No había datos de esperma, por lo que los efectos sobre fertilidad siguen siendo desconocidos.",
    details: `${testicular.sample}. ${testicular.limits}`,
    sources: [{ label: "Estudio original de tejido testicular", meta: `${testicular.journal}, ${testicular.year}`, href: testicular.source }],
  },
];
